export const COLOR_PALETTE = Object.freeze({
  inkBlue: 0x182334,
  fibreBlue: 0x5b91b6,
  roseFibre: 0xb96d8b,
  deepRose: 0x703c59,
  brightSilver: 0xe7e9e7,
  moonSilver: 0xd5dbdd,
  champagneGold: 0xd6b777,
  pearlRose: 0xd899b3,
  mistBlue: 0x86b8cd,
  shadowRose: 0x703c59,
  shadowBlue: 0x182334,
  highlight: 0xfff4dd,
  background: 0x000000,
});

export const VISUAL_THEME = Object.freeze({
  background: COLOR_PALETTE.background,
  postprocessing: {
    pixelRatioCap: 1.35,
    exposure: 1.07,
    bloomStrength: 0.35,
    bloomRadius: 0.2,
    bloomThreshold: 0.92,
  },
  motion: {
    slowBreathPeriod: 10.4,
    secondaryBreathPeriod: 4.15,
    travelingWavePeriod: 18.8,
    environmentalDriftPeriod: 23.7,
  },
  fog: {
    color: COLOR_PALETTE.background,
    density: 0.055,
  },
  cores: {
    a: {
      color: COLOR_PALETTE.champagneGold,
      edgeColor: COLOR_PALETTE.pearlRose,
      size: 0.22,
    },
    b: {
      color: COLOR_PALETTE.moonSilver,
      edgeColor: COLOR_PALETTE.mistBlue,
      size: 0.22,
    },
  },
  ambient: {
    dustCount: 1650,
    coreParticlesPerParticipant: 280,
    relationPathCount: 260,
    particleSize: 0.011,
    dustOpacity: 0.098,
    coreCloudOpacity: 0.218,
    relationOpacity: 0.166,
    idleFadeSpeed: 0.78,
    anchorLagSpeed: 1.15,
    driftSpeed: 0.085,
    coreRadius: 0.46,
    relationReach: 0.16,
    dustCoreColors: [
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.champagneGold,
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.highlight,
    ] as const,
    dustEdgeColors: [
      COLOR_PALETTE.shadowBlue,
      COLOR_PALETTE.shadowRose,
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.pearlRose,
    ] as const,
    aCoreColors: [
      COLOR_PALETTE.champagneGold,
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.pearlRose,
      COLOR_PALETTE.mistBlue,
    ] as const,
    aEdgeColors: [
      COLOR_PALETTE.pearlRose,
      COLOR_PALETTE.shadowBlue,
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.shadowRose,
    ] as const,
    bCoreColors: [
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.champagneGold,
      COLOR_PALETTE.pearlRose,
    ] as const,
    bEdgeColors: [
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.shadowRose,
      COLOR_PALETTE.pearlRose,
      COLOR_PALETTE.shadowBlue,
    ] as const,
  },
  hands: {
    particleSize: 0.0102,
    visibility: {
      particleCountPerHand: 7600,
      basePointScale: 0.88,
      closePointScale: 1.08,
      farPointScale: 0.74,
      minScreenPixels: 1.08,
      baseAlpha: 0.93,
      coreAlpha: 0.98,
      emissiveIntensity: 1.48,
      minLuminance: 0.64,
      resultBoost: 1.44,
      contourCountPerHand: 450,
      contourAlpha: 1.24,
      contourPointScale: 1.12,
      fingertipBoost: 1.18,
      shedFraction: 0.12,
      readabilityOpacity: 0.9,
    },
    scatterRadius: 1.05,
    idleFormation: 0.065,
    idleOpacity: 0.018,
    idleTraceStrength: 0.72,
    inactiveOpacity: 0.00002,
    activeOpacity: 0.82,
    formationSpeed: 1.85,
    disintegrationSpeed: 0.72,
    // The thumb now has one fewer anatomical joint cluster; these sixty points
    // move into the palm plane so the existing 7,600-particle budget is stable.
    palmParticles: 2360,
    wristParticles: 760,
    fingerParticles: [530, 730, 825, 710, 545] as const,
    jointParticlesPerJoint: 60,
    a: {
      color: COLOR_PALETTE.champagneGold,
      edgeColor: COLOR_PALETTE.pearlRose,
      coreColors: [
        COLOR_PALETTE.brightSilver, COLOR_PALETTE.brightSilver,
        COLOR_PALETTE.brightSilver, COLOR_PALETTE.brightSilver,
        COLOR_PALETTE.moonSilver, COLOR_PALETTE.moonSilver,
        COLOR_PALETTE.moonSilver, COLOR_PALETTE.moonSilver, COLOR_PALETTE.moonSilver,
        COLOR_PALETTE.champagneGold, COLOR_PALETTE.champagneGold,
        COLOR_PALETTE.champagneGold, COLOR_PALETTE.champagneGold,
        COLOR_PALETTE.pearlRose, COLOR_PALETTE.pearlRose,
        COLOR_PALETTE.pearlRose, COLOR_PALETTE.pearlRose,
        COLOR_PALETTE.mistBlue, COLOR_PALETTE.mistBlue, COLOR_PALETTE.mistBlue,
      ] as const,
      edgeColors: [
        COLOR_PALETTE.pearlRose,
        COLOR_PALETTE.mistBlue,
        COLOR_PALETTE.shadowRose,
        COLOR_PALETTE.shadowBlue,
      ] as const,
      density: 1,
      brightness: 1.14,
      motionPhase: 0.31,
    },
    b: {
      color: COLOR_PALETTE.moonSilver,
      edgeColor: COLOR_PALETTE.mistBlue,
      coreColors: [
        COLOR_PALETTE.moonSilver, COLOR_PALETTE.moonSilver,
        COLOR_PALETTE.moonSilver, COLOR_PALETTE.moonSilver,
        COLOR_PALETTE.brightSilver, COLOR_PALETTE.brightSilver,
        COLOR_PALETTE.brightSilver, COLOR_PALETTE.brightSilver, COLOR_PALETTE.brightSilver,
        COLOR_PALETTE.champagneGold, COLOR_PALETTE.champagneGold,
        COLOR_PALETTE.champagneGold, COLOR_PALETTE.champagneGold,
        COLOR_PALETTE.mistBlue, COLOR_PALETTE.mistBlue,
        COLOR_PALETTE.mistBlue, COLOR_PALETTE.mistBlue,
        COLOR_PALETTE.pearlRose, COLOR_PALETTE.pearlRose, COLOR_PALETTE.pearlRose,
      ] as const,
      edgeColors: [
        COLOR_PALETTE.mistBlue,
        COLOR_PALETTE.pearlRose,
        COLOR_PALETTE.shadowBlue,
        COLOR_PALETTE.shadowRose,
      ] as const,
      density: 1,
      brightness: 1.12,
      motionPhase: 1.73,
    },
  },
  orbits: {
    particleCount: 780,
    groupCount: 6,
    particleSize: 0.012,
    baseOpacity: 0.18,
    sharedOpacity: 0.248,
    colors: [
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.moonSilver,
      COLOR_PALETTE.champagneGold,
      COLOR_PALETTE.pearlRose,
      COLOR_PALETTE.mistBlue,
    ] as const,
    edgeColors: [
      COLOR_PALETTE.shadowBlue,
      COLOR_PALETTE.shadowRose,
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.pearlRose,
    ] as const,
  },
  bridges: {
    particleCount: 450,
    particleSize: 0.012,
    opacity: 0.318,
  },
  butterflies: {
    count: 14,
    idleVisibleCount: 10,
    maxPerchedPerHand: 3,
    coreColor: COLOR_PALETTE.moonSilver,
    edgeColors: [
      COLOR_PALETTE.mistBlue,
      COLOR_PALETTE.pearlRose,
      COLOR_PALETTE.champagneGold,
      COLOR_PALETTE.shadowBlue,
    ] as const,
    size: 0.13,
    idleOpacity: 0.27,
    soloOpacity: 0.41,
    joinOpacity: 0.47,
    opacitySpeed: 1.15,
    speedMin: 0.74,
    speedMax: 1.08,
    flapAmplitude: 0.78,
    idleSpread: [2.8, 1.5, 1.55] as const,
    gatherRadius: 0.48,
    motionStiffness: 1.05,
    motionDamping: 1.62,
    approachSeconds: [1.8, 3.4] as const,
    perchSeconds: [4, 10] as const,
    takeOffSeconds: [1.6, 2.8] as const,
  },
  staves: [
    {
      name: 'near',
      color: COLOR_PALETTE.moonSilver,
      opacity: 0.5,
      width: 4.55,
      spacing: 0.12,
      segments: 160,
      position: [0, 0.1, 0.34] as const,
      rotation: [-0.025, -0.055, 0.008] as const,
      driftSpeed: 0.095,
      driftAmplitude: 0.12,
      depthAmplitude: 0.13,
      curvature: 0.18,
    },
    {
      name: 'middle',
      color: COLOR_PALETTE.mistBlue,
      opacity: 0.26,
      width: 5.0,
      spacing: 0.105,
      segments: 144,
      position: [-0.61, 0.08, -0.58] as const,
      rotation: [0.024, 0.07, -0.012] as const,
      driftSpeed: 0.066,
      driftAmplitude: 0.105,
      depthAmplitude: 0.11,
      curvature: 0.2,
    },
    {
      name: 'far',
      color: COLOR_PALETTE.pearlRose,
      opacity: 0.15,
      width: 5.8,
      spacing: 0.09,
      segments: 128,
      position: [0.63, 0.12, -2.2] as const,
      rotation: [-0.018, -0.052, 0.014] as const,
      driftSpeed: 0.041,
      driftAmplitude: 0.08,
      depthAmplitude: 0.085,
      curvature: 0.22,
    },
  ],
  filaments: {
    count: 32,
    segmentsPerFilament: 22,
    baseOpacity: 0.174,
    contactOpacity: 0.31,
    colorsA: [COLOR_PALETTE.shadowBlue, COLOR_PALETTE.moonSilver, COLOR_PALETTE.pearlRose] as const,
    colorsB: [COLOR_PALETTE.shadowRose, COLOR_PALETTE.moonSilver, COLOR_PALETTE.mistBlue] as const,
    sharedColors: [COLOR_PALETTE.moonSilver, COLOR_PALETTE.champagneGold] as const,
  },
  weave: {
    lineOpacity: 0.68,
    pointOpacity: 0.72,
    transitionSeconds: 0.82,
    resetTransitionSeconds: 1.42,
  },
  installationWeave: {
    transitionSeconds: 1.02,
    resetTransitionSeconds: 1.38,
    mirrorCount: 8,
  },
  camera: {
    baseZ: 5.75,
    breathZ: 0.018,
    breathY: 0.006,
    focusShiftZ: 0.012,
  },
});

export type StaffTheme = (typeof VISUAL_THEME.staves)[number];
export type HandTheme = typeof VISUAL_THEME.hands;
export type ButterflyTheme = typeof VISUAL_THEME.butterflies;
